FALLBACK_PLAY_LABELS = {
    "PFNA": "First Name",
    "PLNA": "Last Name",
    "PGID": "Player ID",
    "POID": "NFL ID",
    "TGID": "Team ID",
    "CYID": "City ID",
    "PPOS": "Position",
    "PLTY": "Archetype",
    "POVR": "Overall",
    "PAGE": "Age",
    "PHGT": "Height",
    "PWGT": "Weight",
    "PYRP": "Years Pro",
    "PJEN": "Jersey Num.",
    "PCOL": "College",
    "PHTN": "Home Town",
    "PHSN": "Home State",
    "PHAN": "Dom. Hand",
    "PCPH": "Career Phase",
    "PIMP": "Importance",
    "PINJ": "Injury",
    "PYCF": "Confidence",
    "PSXP": "Portrait ID",
    "PGHE": "Face ID",
    "PCMT": "Comment",
    "PFPB": "Pro Bowl",
    "PFHO": "Holdout",
    "ISCN": "Team Captain",
    "PSTM": "Sleeves Temp",
    "PSTN": "Stance",
    "PQBS": "QB Style",
    "PSTY": "Throw Style",
    "EPAV": "Endzone Play",
    "PEPS": "Celebration",
    "PEYE": "Eye Paint",
    "PBRE": "Nasal Strip",
    "PFMK": "Facemask",
    "PHCL": "Hair Color",
    "PHLM": "Helmet",
    "PCON": "Contract Length",
    "PCYL": "Contract Years Left",
    "PCSA": "Current Salary",
    "PTSA": "Total Salary",
    "PVCO": "Previous Contract Length",
    "PVSB": "Previous Bonus",
    "PVTS": "Previous Salary",
    "PSBO": "Signing Bonus Total",
    "PSA0": "Salary Year 0",
    "PSA1": "Salary Year 1",
    "PSA2": "Salary Year 2",
    "PSA3": "Salary Year 3",
    "PSA4": "Salary Year 4",
    "PSA5": "Salary Year 5",
    "PSA6": "Salary Year 6",
    "PSB0": "Bonus Year 0",
    "PSB1": "Bonus Year 1",
    "PSB2": "Bonus Year 2",
    "PSB3": "Bonus Year 3",
    "PSB4": "Bonus Year 4",
    "PSB5": "Bonus Year 5",
    "PSB6": "Bonus Year 6",
    "PACC": "Acceleration",
    "PAGI": "Agility",
    "PAWR": "Awareness",
    "PBCV": "Ball Carrier Vision",
    "PBKT": "Break Tackle",
    "PBSG": "Block Shed",
    "PBSK": "Break Sack",
    "PCAR": "Carry",
    "PCBT": "Catch In Traffic",
    "PCMT": "Comment",
    "PCTH": "Catch",
    "PDRO": "Draft Round",
    "PDRR": "Deep Route Run",
    "PELU": "Elusive",
    "PFMS": "Finesse Moves",
    "PICN": "NFL Icon",
    "PJMP": "Jump",
    "PKAC": "Kick Accuracy",
    "PKPR": "Kick Power",
    "PKRT": "Kick Return",
    "PLBD": "Birthday",
    "PLBK": "Lead Block",
    "PLCI": "Catch In Traffic",
    "PLHT": "Hit Power",
    "PLHW": "Hand Warmer",
    "PLIB": "Impact Block",
    "PLJM": "Juke Move",
    "PLKN": "Left Knee",
    "PLMC": "Man Coverage",
    "PLPE": "Press Cover",
    "PLPO": "Potential",
    "PLPR": "Play Recognition",
    "PLPU": "Pursuit",
    "PLRL": "Release",
    "PLSA": "Stiff Arm",
    "PLSC": "Spec. Catch",
    "PLSM": "Spin Move",
    "PLTL": "Towel",
    "PLTR": "Trucking",
    "PLZC": "Zone Cover",
    "PMRR": "Medium Route Run",
    "PPBF": "Pass Block Finesse",
    "PPBK": "Pass Block",
    "PPBS": "Pass Block Strength",
    "PPLA": "Play Action",
    "PRBF": "Run Block Finesse",
    "PRBK": "Run Block",
    "PRBS": "Run Block Strength",
    "PRKN": "Right Knee",
    "PSHK": "Sock Height",
    "PSPD": "Speed",
    "PSPL": "Left Ankle",
    "PSPR": "Right Ankle",
    "PSTA": "Stamina",
    "PSTR": "Strength",
    "PTAK": "Tackle",
    "PTAD": "Throw Deep",
    "PTAM": "Throw Medium",
    "PTAS": "Throw Short",
    "PTEN": "Tendency",
    "PTGH": "Toughness",
    "PTHA": "Throw Accuracy",
    "PTHP": "Throw Power",
    "PTOR": "Throw On Run",
    "PTUP": "Throw Under Pressure",
    "SRRN": "Short Route Run",
    "TRBH": "Big Hitter",
    "TRBR": "Bull Rush",
    "TRCB": "Covers Ball",
    "TRCL": "Clutch",
    "TRCT": "Possession Catch",
    "TRDO": "Drops Open pass",
    "TRDS": "DL Spin",
    "TRFB": "Keep Feet In Bounds",
    "TRFP": "Force Passes",
    "TRFY": "Fight Yards",
    "TRHM": "High Motor",
    "TRIC": "Penalty",
    "TRJR": "Aggressive Catch",
    "TRPB": "Plays Ball",
    "TRSB": "Strips Ball",
    "TRSC": "Sideline Catch",
    "TRSP": "Sense Pressure",
    "TRSW": "DL Swim",
    "TRTA": "Throw Away",
    "TRTR": "Tuck & Run",
    "TRTS": "Throw Spiral",
    "TRWU": "Run After Catch",
}

FALLBACK_TEAM_LABELS = {
    "TDNA": "Team Name",
    "TLNA": "Team Long Name",
    "TMNC": "Team Nick Name",
    "TMAN": "Team Abbrev",
    "TGID": "Team ID",
    "TMID": "Mascot ID",
    "TCID": "City ID",
    "TORD": "Team Roster Order",
    "TCIN": "Conference",
    "TCNA": "City",
    "TDPB": "Defensive Playbook",
    "TOPB": "Offensive Playbook",
    "TCRP": "Team Color Primary",
    "TCRD": "Team Color Secondary",
    "TMSO": "Team Motto Short",
    "TMST": "Team Motto",
    "TMHO": "Team Hashtag",
    "TMHT": "Team Brotherhood",
    "TOID": "Team Original ID",
    "TOQB": "QB Rating",
    "TORB": "RB Rating",
    "TOWR": "WR Rating",
    "TOOL": "OL Rating",
    "TODL": "DL Rating",
    "TOLB": "LB Rating",
    "TODB": "DB Rating",
    "TOOF": "Offensive Rating",
    "TODF": "Defensive Rating",
    "TOSP": "ST Rating",
    "THAR": "Home Field Advantage",
    "TBCR": "Primary RED",
    "TBCG": "Primary Green",
    "TBCB": "Primary Blue",
    "TB2R": "Secondary RED",
    "TB2G": "Secondary Green",
    "TB2B": "Secondary Blue",
    "TRQB": "QB Rating",
    "TRRB": "RB Rating",
    "TWRR": "WR Rating",
    "TROL": "OL Rating",
    "TRDL": "DL Rating",
    "TRLB": "LB Rating",
    "TRDB": "DB Rating",
    "TROF": "Offensive Rating",
    "TRDE": "Defensive Rating",
    "TRST": "ST Rating",
    "TROV": "Overall Rating",
    "SGID": "Stadium ID",
    "TRV1": "Team Rival 1",
    "TRV2": "Team Rival 2",
    "TRV3": "Team Rival 3",
    "TSNA": "Team Short Name",
    "TSHO": "Team Shoe Color",
    "TTYP": "Team Type",
    "TVIS": "Visibility",
}

FALLBACK_TCPS_LABELS = {
    "TGID": "Team ID",
    "TCRK": "Coaches Rankings",
    "TMRK": "Media Rankings",
}
